"""Inactive durable-mailbox synchronization package.

Nothing in this package opens a database connection, reads runtime secrets,
calls a mail provider, or activates an API route.
"""

from .repository_contract import (
    BackfillState,
    BodyCacheOutcome,
    BodyState,
    BodyWrite,
    BootstrapState,
    CachedBody,
    DeltaCommitOutcome,
    derive_locator_digest,
    derive_message_id,
    derive_outbox_event_id,
    GenerationActivation,
    GenerationActivationOutcome,
    MailboxBinding,
    MailboxParty,
    MailboxProvider,
    MailboxRepository,
    MailboxScope,
    MessageIdentity,
    MessageMutation,
    MessageMutationKind,
    MessageProjection,
    MessageWrite,
    OutboxEvent,
    OutboxEventType,
    ProviderDeltaCommit,
    SyncCursor,
)
from .schema import (
    MAILBOX_SCHEMA,
    MAILBOX_SCHEMA_VERSION,
    MAILBOX_TABLES,
    mailbox_change_outbox,
    mailbox_message_bodies,
    mailbox_messages,
    mailbox_sync_cursor,
    mailbox_sync_state,
    metadata,
)

__all__ = (
    "BackfillState",
    "BodyCacheOutcome",
    "BodyState",
    "BodyWrite",
    "BootstrapState",
    "CachedBody",
    "DeltaCommitOutcome",
    "derive_locator_digest",
    "derive_message_id",
    "derive_outbox_event_id",
    "GenerationActivation",
    "GenerationActivationOutcome",
    "MAILBOX_SCHEMA",
    "MAILBOX_SCHEMA_VERSION",
    "MAILBOX_TABLES",
    "MailboxBinding",
    "MailboxParty",
    "MailboxProvider",
    "MailboxRepository",
    "MailboxScope",
    "MessageIdentity",
    "MessageMutation",
    "MessageMutationKind",
    "MessageProjection",
    "MessageWrite",
    "OutboxEvent",
    "OutboxEventType",
    "ProviderDeltaCommit",
    "SyncCursor",
    "mailbox_change_outbox",
    "mailbox_message_bodies",
    "mailbox_messages",
    "mailbox_sync_cursor",
    "mailbox_sync_state",
    "metadata",
)
