import assert from "node:assert/strict";
import { test } from "node:test";
import { buildExactNotificationMessageIndex, createNotificationNavigator, exactNotificationSourceKey } from "./notificationNavigation";
import { buildExactMailboxMessageSeed, captureExactMailboxMessageTicket, reduceExactMailboxMessagePublication } from "./exactMailboxMessageStore";
import { notification, scope, google, imap, exactResponse, collaboration, deferred, tick } from "./notificationsTestFixtures.test";
function fixture(row = notification()) {
  const response = exactResponse(row.sourceRef as typeof google | typeof imap);
  const calls: string[] = [];
  let currentScope: typeof scope | null = scope;
  let mailbox: { provider: string; configRevision: number } | null = { provider: row.sourceRef.provider, configRevision: 1 };
  const handlers = {
    lookup: () => ({ message: response.message, folder: "Inbox" as const }) as any,
    fetchExact: async () => { calls.push("cold"); return { status: "success", response } as any; },
    display: async (request: any) => { calls.push(request.collaboration ? "collaboration displayed" : "mail displayed"); return true; },
    read: async (id: string) => { calls.push("read:" + id); return { status: "success", collaboration: collaboration(row) } as any; },
    mark: async () => { calls.push("mark"); return true; },
    augment: () => { calls.push("augment"); return { message: response.message, folder: "Inbox" as const }; },
  };
  const navigator = createNotificationNavigator({
    getScope: () => currentScope, getMailbox: id => id === row.mailboxId ? mailbox : null,
    lookup: () => handlers.lookup(), fetchExact: (..._args) => handlers.fetchExact(),
    display: request => handlers.display(request), readCollaboration: id => handlers.read(id),
    markRead: () => handlers.mark(), augment: () => handlers.augment(), feedback: message => { if (message) calls.push("feedback:" + message); },
  });
  return { navigator, handlers, calls, response, setScope: (next: typeof scope | null) => { currentScope = next; }, setMailbox: (next: typeof mailbox) => { mailbox = next; } };
}
for (const source of [google, imap]) {
  test(`loaded ${source.provider}: exact mail, historical Collaboration, activity then mark`, async () => { const row = notification(1, { sourceRef: source }); const f = fixture(row); assert.equal(await f.navigator.open(row), true); assert.deepEqual(f.calls, ["mail displayed", "read:" + row.collaborationId, "collaboration displayed", "mark"]); });
  test(`cold ${source.provider} uses C3D0 and augmentation before display`, async () => { const row = notification(1, { sourceRef: source }); const f = fixture(row); f.handlers.lookup = () => undefined; assert.equal(await f.navigator.open(row), true); assert.deepEqual(f.calls.slice(0, 3), ["cold", "augment", "mail displayed"]); });
}
for (const [name, mutate] of [
  ["Google identity", (response: any) => { response.message.providerMessageId = "wrong"; }],
  ["mailbox", (response: any) => { response.mailboxId = "wrong"; }],
  ["source reference", (response: any) => { response.sourceRef = { ...google, providerMessageId: "wrong" }; }],
] as const) test(`cold ${name} mismatch fails without augmentation or mark`, async () => { const f = fixture(); f.handlers.lookup = () => undefined; mutate(f.response); assert.equal(await f.navigator.open(notification()), false); assert.ok(!f.calls.includes("augment")); assert.ok(!f.calls.includes("mark")); });
for (const code of ["source_changed", "message_not_found", "provider_mismatch", "service_unavailable"]) test(`cold ${code} fails safely without retry`, async () => { const row = notification(1, { sourceRef: imap }); const f = fixture(row); f.handlers.lookup = () => undefined; let count = 0; f.handlers.fetchExact = async () => { count++; return { status: code }; }; assert.equal(await f.navigator.open(row), false); assert.equal(count, 1); assert.ok(!f.calls.includes("mark")); });
test("wrong mailbox fails before lookup", async () => { const f = fixture(); assert.equal(await f.navigator.open(notification(1, { mailboxId: "other" })), false); assert.ok(!f.calls.includes("mark")); });
test("wrong workspace fails before lookup", async () => { const f = fixture(); assert.equal(await f.navigator.open(notification(1, { workspaceId: "wsp_" + "Z".repeat(22) })), false); assert.ok(!f.calls.includes("mark")); });
test("provider mismatch fails before fetch", async () => { const f = fixture(); f.setMailbox({ provider: "custom_imap", configRevision: 1 }); assert.equal(await f.navigator.open(notification()), false); assert.ok(!f.calls.includes("cold")); });
test("loaded wrong exact identity never falls back to subject sender or timestamp", async () => { const f = fixture(); f.handlers.lookup = () => ({ message: { ...f.response.message, providerMessageId: "wrong" }, folder: "Inbox" }); assert.equal(await f.navigator.open(notification()), false); assert.ok(!f.calls.includes("cold")); assert.ok(!f.calls.includes("mark")); });
test("ambiguous loaded identity fails closed", async () => { const f = fixture(); f.handlers.lookup = () => null; assert.equal(await f.navigator.open(notification()), false); assert.ok(!f.calls.includes("cold")); });
for (const field of ["collaborationId", "mailboxId"]) test(`canonical read wrong ${field} never displays or marks`, async () => { const f = fixture(); f.handlers.read = async () => ({ status: "success", collaboration: { ...collaboration(), [field]: "wrong" } }); assert.equal(await f.navigator.open(notification()), false); assert.ok(!f.calls.includes("collaboration displayed")); assert.ok(!f.calls.includes("mark")); });
test("null activity opens exact Collaboration then marks", async () => { const row = notification(1, { kind: "collaboration_started", activityId: null }); const f = fixture(row); assert.equal(await f.navigator.open(row), true); assert.ok(f.calls.includes("read:" + row.collaborationId)); assert.equal(f.calls.at(-1), "mark"); });
test("missing activity stays unread with safe feedback", async () => { const f = fixture(); f.handlers.read = async () => ({ status: "success", collaboration: { ...collaboration(), messages: [] } }); assert.equal(await f.navigator.open(notification()), false); assert.ok(f.calls.includes("feedback:This update is no longer available.")); assert.ok(!f.calls.includes("mark")); });
test("duplicate canonical activity ID fails closed", async () => { const f = fixture(); f.handlers.read = async () => ({ status: "success", collaboration: { ...collaboration(), messages: [...collaboration().messages, ...collaboration().messages] } }); assert.equal(await f.navigator.open(notification()), false); assert.ok(!f.calls.includes("mark")); });
for (const code of ["not_found", "forbidden", "unauthorized", "service_unavailable"]) test(`Collaboration ${code} remains unread`, async () => { const f = fixture(); f.handlers.read = async () => ({ status: code }); assert.equal(await f.navigator.open(notification()), false); assert.ok(!f.calls.includes("mark")); });
test("click and exact mail alone do not mark; waits for canonical visible display", async () => { const f = fixture(), mail = deferred(), read = deferred(), activity = deferred(); f.handlers.display = request => request.collaboration ? activity.promise : mail.promise; f.handlers.read = () => read.promise; const opened = f.navigator.open(notification()); assert.deepEqual(f.calls, []); await tick(); assert.ok(!f.calls.includes("mark")); mail.resolve(true); await tick(); assert.ok(!f.calls.includes("mark")); read.resolve({ status: "success", collaboration: collaboration() }); await tick(); assert.ok(!f.calls.includes("mark")); activity.resolve(true); assert.equal(await opened, true); assert.deepEqual(f.calls, ["mark"]); });
for (const stage of ["mail", "collaboration"]) test(`failed ${stage} display never marks`, async () => { const f = fixture(); f.handlers.display = async request => stage === "mail" ? false : !request.collaboration; assert.equal(await f.navigator.open(notification()), false); assert.ok(!f.calls.includes("mark")); });
test("same current navigation activation dedupes", async () => { const f = fixture(), pending = deferred(); f.handlers.read = () => pending.promise; const a = f.navigator.open(notification()), b = f.navigator.open(notification()); assert.equal(a, b); pending.resolve({ status: "success", collaboration: collaboration() }); await a; assert.equal(f.calls.filter(call => call === "mark").length, 1); });
test("click A then B fences A after cold fetch", async () => { const f = fixture(), pending = deferred(); f.handlers.lookup = () => undefined; f.handlers.fetchExact = () => pending.promise; const a = f.navigator.open(notification()); await tick(); f.handlers.lookup = () => ({ message: f.response.message, folder: "Inbox" }); const b = f.navigator.open(notification(2)); pending.resolve({ status: "success", response: f.response }); assert.equal(await a, false); assert.equal(await b, true); assert.equal(f.calls.filter(call => call === "mark").length, 1); assert.ok(!f.calls.includes("augment")); });
test("click A then B fences A after canonical read", async () => { const f = fixture(), pending = deferred(); f.handlers.read = () => pending.promise; const a = f.navigator.open(notification()); await tick(); f.handlers.read = async () => ({ status: "success", collaboration: collaboration() }); const b = f.navigator.open(notification(2)); pending.resolve({ status: "success", collaboration: collaboration() }); assert.equal(await a, false); assert.equal(await b, true); assert.equal(f.calls.filter(call => call === "collaboration displayed").length, 1); });
for (const [name, next] of [["account", { ...scope, accountId: "usr_" + "B".repeat(21) + "A" }], ["workspace", { ...scope, workspaceId: "wsp_" + "Z".repeat(22) }]] as const) test(`${name} switch fences navigation`, async () => { const f = fixture(), pending = deferred(); f.handlers.read = () => pending.promise; const a = f.navigator.open(notification()); await tick(); f.setScope(next); pending.resolve({ status: "success", collaboration: collaboration() }); assert.equal(await a, false); assert.ok(!f.calls.includes("mark")); });
test("mailbox connection revision change fences cold publication", async () => { const f = fixture(), pending = deferred(); f.handlers.lookup = () => undefined; f.handlers.fetchExact = () => pending.promise; const a = f.navigator.open(notification()); await tick(); f.setMailbox({ provider: "google", configRevision: 2 }); pending.resolve({ status: "success", response: f.response }); assert.equal(await a, false); assert.ok(!f.calls.includes("augment")); });
test("mark failure reports safe feedback", async () => { const f = fixture(); f.handlers.mark = async () => false; assert.equal(await f.navigator.open(notification()), false); assert.ok(f.calls.some(call => call.includes("could not be marked as read"))); });
test("exact lookup uses canonical provider keys, not display fields", () => { const a = exactResponse().message, b = { ...exactResponse(imap).message, id: "imap-renderer" }; const collections = { Inbox: [a, b], Drafts: [], Sent: [], Archive: [], Filtered: [], Spam: [], Trash: [] }; const index = buildExactNotificationMessageIndex({ main: collections }); assert.equal(index.get(exactNotificationSourceKey("main", google))?.message, a); assert.equal(index.get(exactNotificationSourceKey("main", imap))?.message, b); assert.equal(index.get(exactNotificationSourceKey("other", google)), undefined); assert.equal(index.get(exactNotificationSourceKey("main", { ...imap, uidValidity: "24" })), undefined); });
for (const source of [google, imap]) test(`actual C3D0 ${source.provider} publication augments without replacing mailbox`, () => {
  const response = exactResponse(source), unrelated = { ...response.message, id: "unrelated", ...(source.provider === "google" ? { providerMessageId: "other" } : { imapUid: "43" }) };
  const collections = { Inbox: [unrelated], Drafts: [], Sent: [], Archive: [], Filtered: [], Spam: [], Trash: [] };
  const currentScope = { ...scope, mailboxId: "main", provider: source.provider, configRevision: 1, generation: 1 };
  const current = { scope: currentScope, mailboxes: { main: collections }, selection: null };
  const ticket = captureExactMailboxMessageTicket(currentScope, source);
  const next = reduceExactMailboxMessagePublication(current, ticket, response, buildExactMailboxMessageSeed(response));
  assert.equal(next.mailboxes.main.Inbox.length, 2); assert.equal(next.mailboxes.main.Inbox[0], unrelated); assert.equal(next.mailboxes.main.Archive, collections.Archive);
  const again = reduceExactMailboxMessagePublication(next, ticket, response, buildExactMailboxMessageSeed(response)); assert.equal(again.mailboxes.main.Inbox.length, 2);
});
test("same-tick A then B starts no stale cold request", async () => { const f = fixture(); f.handlers.lookup = () => undefined; const a = f.navigator.open(notification()), b = f.navigator.open(notification(2)); assert.equal(await a, false); assert.equal(await b, true); assert.equal(f.calls.filter(call => call === "cold").length, 1); });
test("renderer ID collision with a message lacking provider identity fails exact lookup", () => { const message = exactResponse().message, other = { ...message, providerMessageId: undefined }; const index = buildExactNotificationMessageIndex({ main: { Inbox: [other, message], Drafts: [], Sent: [], Archive: [], Filtered: [], Spam: [], Trash: [] } }); assert.equal(index.get(exactNotificationSourceKey("main", google)), null); });
test("bounded navigation finishes on deadline even if canonical read never settles", async () => { const f = fixture(); const calls: string[] = []; const navigator = createNotificationNavigator({ getScope: () => scope, getMailbox: () => ({ provider: "google", configRevision: 0 }), lookup: () => ({ message: f.response.message, folder: "Inbox" }), augment: () => null, display: async () => true, readCollaboration: () => new Promise(() => {}), markRead: async () => { calls.push("mark"); return true; }, feedback: message => { if (message) calls.push(message); } }, 10); assert.equal(await navigator.open(notification()), false); assert.ok(!calls.includes("mark")); assert.equal(calls.length, 1); });
