import assert from "node:assert/strict";
import { test } from "node:test";
import { createWorkspaceNotificationStore } from "./workspaceNotificationStore";
import { notification, page, scope, success, deferred, tick, time } from "./notificationsTestFixtures.test";
function fixture() {
  const calls = { summary: 0, list: [] as (string | null)[], mark: [] as string[] };
  const handlers = { summary: async () => success({ v: 1 as const, unreadCount: 87 }), list: async (_cursor: string | null) => success(page()), mark: async (id: string) => success({ v: 1 as const, unreadCount: 86, notification: notification(1, { notificationId: id, readAt: time }) }) };
  const store = createWorkspaceNotificationStore(scope, {
    summary: () => { calls.summary++; return handlers.summary(); },
    list: (_workspace, cursor) => { calls.list.push(cursor); return handlers.list(cursor); },
    markRead: (_workspace, id) => { calls.mark.push(id); return handlers.mark(id); },
  }, () => now);
  let now = 100000;
  return { store, calls, handlers, setNow: (value: number) => { now = value; } };
}
test("construction does not load records; workspace startup exactly one summary", async () => { const f = fixture(); assert.equal(f.calls.summary, 0); await f.store.start(); await f.store.start(); assert.equal(f.calls.summary, 1); assert.deepEqual(f.calls.list, []); assert.equal(f.store.getSnapshot().unreadCount, 87); });
test("concurrent startup summary dedupes same promise", async () => { const f = fixture(), pending = deferred(); f.handlers.summary = () => pending.promise; const first = f.store.start(); assert.equal(first, f.store.start()); pending.resolve(success({ v: 1, unreadCount: 103 })); await first; assert.equal(f.calls.summary, 1); assert.equal(f.store.getSnapshot().unreadCount, 103); });
test("Dashboard and workbench concurrent first page share request", async () => { const f = fixture(), pending = deferred(); f.handlers.list = () => pending.promise; const first = f.store.ensureFirstPage("dashboard"); assert.equal(first, f.store.ensureFirstPage("workbench")); pending.resolve(success(page())); await first; assert.deepEqual(f.calls.list, [null]); });
test("no page before record consumer", async () => { const f = fixture(); await f.store.start(); await tick(); assert.deepEqual(f.calls.list, []); await f.store.ensureFirstPage("dashboard"); assert.deepEqual(f.calls.list, [null]); });
test("Dashboard reuses first page regardless of age", async () => { const f = fixture(); await f.store.ensureFirstPage("workbench"); f.setNow(999999); await f.store.ensureFirstPage("dashboard"); assert.equal(f.calls.list.length, 1); });
test("workbench revisit refreshes once after sixty seconds", async () => { const f = fixture(); await f.store.ensureFirstPage("workbench"); f.setNow(159999); await f.store.ensureFirstPage("workbench"); assert.equal(f.calls.list.length, 1); f.setNow(160000); await f.store.ensureFirstPage("workbench"); await f.store.ensureFirstPage("workbench"); assert.equal(f.calls.list.length, 2); });
test("one Load more click requests one unmodified cursor and never drains", async () => { const f = fixture(); f.handlers.list = async cursor => success(cursor === null ? page([notification(1)], 87, "cursor+/=") : page([notification(2)], 87, "third")); await f.store.refresh(); assert.deepEqual(f.calls.list, [null]); await f.store.loadMore(); assert.deepEqual(f.calls.list, [null, "cursor+/="]); assert.equal(f.store.getSnapshot().nextCursor, "third"); });
test("duplicate concurrent load-more blocked", async () => { const f = fixture(); f.handlers.list = async () => success(page([notification()], 87, "more")); await f.store.refresh(); const pending = deferred(); f.handlers.list = () => pending.promise; const first = f.store.loadMore(); assert.equal(first, f.store.loadMore()); pending.resolve(success(page([notification(2)]))); await first; assert.equal(f.calls.list.length, 2); });
test("failed page preserves old rows and cursor", async () => { const f = fixture(); f.handlers.list = async () => success(page([notification()], 87, "more")); await f.store.refresh(); f.handlers.list = async () => ({ status: "service_unavailable" } as any); await f.store.loadMore(); assert.equal(f.store.getSnapshot().orderedIds.length, 1); assert.equal(f.store.getSnapshot().nextCursor, "more"); assert.equal(f.store.getSnapshot().loadMoreError, true); });
test("failed explicit refresh preserves old rows and is retryable", async () => { const f = fixture(); await f.store.refresh(); f.handlers.list = async () => ({ status: "service_unavailable" } as any); await f.store.refresh(); assert.equal(f.store.getSnapshot().byId.size, 1); assert.equal(f.store.getSnapshot().listError, true); f.handlers.list = async () => success(page([])); await f.store.refresh(); assert.equal(f.store.getSnapshot().byId.size, 0); assert.equal(f.store.getSnapshot().listError, false); });
test("pagination dedupes notification IDs and preserves newest first", async () => { const f = fixture(); f.handlers.list = async cursor => success(cursor === null ? page([notification(1), notification(2)], 87, "more") : page([notification(2), notification(3)])); await f.store.refresh(); await f.store.loadMore(); assert.deepEqual(f.store.getSnapshot().orderedIds, [1, 2, 3].map(i => notification(i).notificationId)); });
test("non-advancing page cannot drain repeatedly", async () => { const f = fixture(); f.handlers.list = async () => success(page([notification()], 87, "more")); await f.store.refresh(); await f.store.loadMore(); assert.equal(f.store.getSnapshot().loadMoreError, true); assert.equal(f.store.getSnapshot().orderedIds.length, 1); });
test("cyclic cursor is rejected without losing rows", async () => { const f = fixture(); const pages = [page([notification(1)], 87, "a"), page([notification(2)], 87, "b"), page([notification(3)], 87, "a")]; f.handlers.list = async () => success(pages.shift()!); await f.store.refresh(); await f.store.loadMore(); await f.store.loadMore(); assert.equal(f.store.getSnapshot().loadMoreError, true); assert.equal(f.store.getSnapshot().byId.size, 2); });
for (const [name, next] of [["account", { ...scope, accountId: "usr_" + "B".repeat(21) + "A" }], ["workspace", { ...scope, workspaceId: "wsp_" + "Z".repeat(22) }]] as const) {
  test(`${name} switch clears rows/count immediately and fences old summary/page`, async () => {
    const f = fixture(); await f.store.refresh(); const pendingSummary = deferred(), pendingPage = deferred();
    f.handlers.summary = () => pendingSummary.promise; f.handlers.list = () => pendingPage.promise;
    const oldSummary = f.store.start(), oldPage = f.store.refresh();
    f.store.setScope(next); assert.equal(f.store.getSnapshot().unreadCount, 0); assert.equal(f.store.getSnapshot().byId.size, 0); assert.equal(f.store.getSnapshot().scope, next);
    pendingPage.resolve(success(page())); pendingSummary.resolve(success({ v: 1, unreadCount: 12 })); await oldSummary; await oldPage;
    assert.equal(f.store.getSnapshot().byId.size, 0); assert.equal(f.calls.summary, 2);
  });
}
test("A to B to A fences first A", async () => { const f = fixture(), pending = deferred(); f.handlers.list = () => pending.promise; const old = f.store.refresh(); f.store.setScope({ ...scope, workspaceId: "wsp_" + "Z".repeat(22) }); f.store.setScope(scope); pending.resolve(success(page())); await old; assert.equal(f.store.getSnapshot().byId.size, 0); });
test("mark-read success publishes returned readAt and unreadCount without summary", async () => { const f = fixture(); await f.store.refresh(); assert.equal(await f.store.markRead(notification().notificationId), true); assert.equal(f.store.getSnapshot().byId.get(notification().notificationId)?.readAt, time); assert.equal(f.store.getSnapshot().unreadCount, 86); assert.equal(f.calls.summary, 0); });
test("mark-read failure leaves readAt/count unchanged", async () => { const f = fixture(); await f.store.refresh(); f.handlers.mark = async () => ({ status: "forbidden" } as any); assert.equal(await f.store.markRead(notification().notificationId), false); assert.equal(f.store.getSnapshot().byId.get(notification().notificationId)?.readAt, null); assert.equal(f.store.getSnapshot().unreadCount, 87); });
test("duplicate mark-read while in flight shares promise", async () => { const f = fixture(), pending = deferred(); await f.store.refresh(); f.handlers.mark = () => pending.promise; const first = f.store.markRead(notification().notificationId); assert.equal(first, f.store.markRead(notification().notificationId)); await tick(); assert.equal(f.calls.mark.length, 1); pending.resolve(success({ v: 1, unreadCount: 86, notification: notification(1, { readAt: time }) })); await first; assert.equal(f.store.getSnapshot().markReadIds.size, 0); });
test("read notifications reopen without another mutation", async () => { const f = fixture(); await f.store.refresh(); await f.store.markRead(notification().notificationId); await f.store.markRead(notification().notificationId); assert.equal(f.calls.mark.length, 1); });
test("stale summary and list cannot undo a successful mark-read", async () => { const f = fixture(); await f.store.refresh(); const pendingSummary = deferred(), pendingPage = deferred(); f.handlers.summary = () => pendingSummary.promise; f.handlers.list = () => pendingPage.promise; const a = f.store.start(), b = f.store.refresh(); await f.store.markRead(notification().notificationId); pendingSummary.resolve(success({ v: 1, unreadCount: 87 })); pendingPage.resolve(success(page())); await a; await b; assert.equal(f.store.getSnapshot().unreadCount, 86); assert.equal(f.store.getSnapshot().byId.get(notification().notificationId)?.readAt, time); });
test("concurrent different marks serialize server count responses", async () => { const f = fixture(), pending = deferred(); f.handlers.list = async () => success(page([notification(), notification(2)])); await f.store.refresh(); f.handlers.mark = id => id === notification().notificationId ? pending.promise : Promise.resolve(success({ v: 1, unreadCount: 85, notification: notification(2, { readAt: time }) })); const a = f.store.markRead(notification().notificationId), b = f.store.markRead(notification(2).notificationId); await tick(); assert.equal(f.calls.mark.length, 1); pending.resolve(success({ v: 1, unreadCount: 86, notification: notification(1, { readAt: time }) })); await a; await b; assert.equal(f.store.getSnapshot().unreadCount, 85); });
test("scope switch fences mark-read publication", async () => { const f = fixture(), pending = deferred(); await f.store.refresh(); f.handlers.mark = () => pending.promise; const old = f.store.markRead(notification().notificationId); await tick(); f.store.setScope(null); pending.resolve(success({ v: 1, unreadCount: 86, notification: notification(1, { readAt: time }) })); assert.equal(await old, false); assert.equal(f.store.getSnapshot().unreadCount, 0); assert.equal(f.store.getSnapshot().byId.size, 0); });
test("queued mark revalidates navigation before HTTP", async () => { const f = fixture(); await f.store.refresh(); let current = true; const mark = f.store.markRead(notification().notificationId, () => current); current = false; assert.equal(await mark, false); assert.equal(f.calls.mark.length, 0); });
test("opening sections and rendering rows marks zero notifications", async () => { const f = fixture(); await f.store.start(); await f.store.ensureFirstPage("dashboard"); await f.store.ensureFirstPage("workbench"); f.store.getSnapshot().orderedIds.map(id => f.store.getSnapshot().byId.get(id)); assert.deepEqual(f.calls.mark, []); });
test("no records, no cursor: loadMore does nothing", async () => { const f = fixture(); await f.store.loadMore(); assert.equal(f.calls.list.length, 0); });
