// Local fixture: production modal JSX, layer and close guard; real AccessPanel and owner clients.
// Mailbox/composer/lifecycle state adapters below are fixture-only. No Production traffic.
// From frontend: PLAYWRIGHT_MODULE=/installed/playwright/index.mjs node src/components/collaboration/CollaborationWorkspace.polish.web.test.mjs
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import http from 'node:http';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {build} from 'esbuild';import postcss from 'postcss';import tailwind from 'tailwindcss';import config from '../../../tailwind.config.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const dir=fileURLToPath(new URL('.',import.meta.url)),baseline=process.env.C3P1_BASELINE==='1';
const source=fs.readFileSync(baseline?'/private/tmp/c3p1-workspace-before.tsx':path.join(dir,'../workspace/WorkspaceShell.tsx'),'utf8');const access=fs.readFileSync(baseline?'/private/tmp/c3p1-access-before.tsx':path.join(dir,'CollaborationAccessPanel.tsx'),'utf8');
function between(s,a,b){const i=s.indexOf(a),j=s.indexOf(b,i);assert.ok(i>=0&&j>i,a);return s.slice(i,j);}
const modal=between(source,'        {activeCollaborationMessage\n          ? createPortal(','\n        <SettingsConfirmationModal');
const layer=between(source,'function WorkspaceModalLayer({','function SettingsModalShell({');const locks=between(source,'let workspaceModalLockCount','const weekdayIndexMap');const label=between(source,'function getCollaborationOwnerStateLabel(','function getCollaborationOwnerInternalNoteFailureMessage(');const guard=between(source,'  const requestCloseCollaborationOverlay = () =>','  const applyCanonicalCollaborationAccessResult = (');
const cta=between(source,'        <button\n          type="button"\n          '+(baseline?'className={collaborationCompactPrimaryActionButtonClass}':'data-open-collaboration'),'\n      );\n    }\n    const sourceMailboxId');
const buttonStyles=['primaryActionSurfaceClass','navigationCloseBackButtonClass','mailboxPrimaryActionButtonClass','mailboxNavigationBackButtonClass','collaborationCompactPrimaryActionButtonClass','collaborationCompactDisabledActionButtonClass','collaborationCompactTertiaryActionButtonClass'].map(name=>{const begin=source.indexOf('const '+name+' ='),end=source.indexOf(';',begin)+1;assert.ok(begin>=0&&end>begin);return source.slice(begin,end)}).join('\n');
const fixture=`import React,{useState,useRef,useEffect,useLayoutEffect} from 'react';import {createRoot} from 'react-dom/client';import {createPortal} from 'react-dom';import {CollaborationAccessPanel} from './CollaborationAccessPanel';import {prepareSharedCollaborationMessageForOwner,prepareInternalCollaborationMessageForOwner,resolveCollaborationForOwner,reopenCollaborationForOwner} from '../../lib/collaborationOwnerWriteApi';
${locks}\n${layer}\n${label}
${buttonStyles}
const id='A'.repeat(22),owner='usr_'+'A'.repeat(22),teammate='usr_'+'B'.repeat(21)+'A',extra='usr_'+'C'.repeat(21)+'A',time=1800000000000;
const original={collaborationId:id,mailboxId:'mailbox-google',state:'needs_review',createdAt:time-2000,updatedAt:time,source:{subject:'Autumn launch — final proposal',senderDisplay:'Alex Rivera',fromDisplay:'alex@example.test',timestamp:'2027-01-15T08:00:00Z',bodyText:'Review the launch plan.'},viewerAccess:'owner',participants:[{userId:owner,displayName:'Morgan Lee',access:'owner'},{userId:teammate,displayName:'Sam Taylor',access:'participant'}],externalGuests:[{inviteId:'I'.repeat(22),status:'active',displayName:'Alex Rivera',invitedEmail:'alex@example.test',expiresAt:1900000000},{inviteId:'J'.repeat(22),status:'pending',invitedEmail:'casey@example.test',expiresAt:1900000000},{inviteId:'K'.repeat(22),status:'revoked',displayName:'Previous reviewer',expiresAt:1900000000},{inviteId:'L'.repeat(22),status:'expired',displayName:'Earlier invitation',expiresAt:1900000000},{inviteId:'N'.repeat(22),status:'logged_out',displayName:'Former guest',expiresAt:1900000000}],messages:[{id:'M'.repeat(22),authorDisplayName:'Morgan Lee',authorRole:'Cuevion user',visibility:'shared',text:'The proposal is ready. Could you check the launch dates?',timestamp:time-1000},{id:'O'.repeat(22),authorDisplayName:'Sam Taylor',authorRole:'Cuevion user',visibility:'internal',text:'Budget approved internally. Keep the contingency with the team.',timestamp:time}]};
let server=structuredClone(original);window.__calls=[];window.__intervals=0;const interval=window.setInterval;window.setInterval=(...args)=>{window.__intervals++;return interval(...args)};
window.fetch=async(url,init)=>{if(url!=='/api/collaboration/owner')throw Error('Unexpected network');const b=JSON.parse(init.body);window.__calls.push(b);const reply=(data,status=200)=>new Response(JSON.stringify({ok:true,data}),{status});if(b.operation==='csrf')return reply({csrfToken:'csrf-token',expiresAt:1900000000});if(b.collaborationId&&b.collaborationId!==id)throw Error('Wrong collaboration ID');
if(b.operation==='add_participant'){server.participants.push({userId:b.participantUserId,displayName:'Jamie Chen',access:'participant'});return reply({collaboration:server});}
if(b.operation==='issue_guest_invite'||b.operation==='create_with_guest'){const invitation={inviteId:'Q'.repeat(22),collaborationId:id,allowedActions:['read','reply'],identityAssurance:'link_possession',expiresAt:1900000000,status:'active',...(b.invitedEmail?{invitedEmail:b.invitedEmail}:{})};server.externalGuests.push({inviteId:invitation.inviteId,status:'pending',expiresAt:invitation.expiresAt,...(b.invitedEmail?{invitedEmail:b.invitedEmail}:{})});return reply({...(b.operation==='create_with_guest'?{created:true}:{}),invitationCreated:true,collaboration:server,invitation,token:'T'.repeat(43)},201);}
if(b.operation==='revoke_guest_invite'){const invitation=server.externalGuests.find(g=>g.inviteId===b.inviteId);invitation.status='revoked';return reply({collaboration:server,invitation});}
if(b.operation==='resolve'||b.operation==='reopen'){server.state=b.operation==='resolve'?'resolved':'note_only';server.updatedAt++;return reply({changed:true,collaboration:server});}
if(b.operation.startsWith('append_')){const message={id:String.fromCharCode(82+server.messages.length).repeat(22),authorDisplayName:'Morgan Lee',authorRole:'Cuevion user',text:b.text,visibility:b.operation==='append_internal'?'internal':'shared',timestamp:++server.updatedAt};server.messages.push(message);return reply({message,updatedAt:server.updatedAt});}throw Error('Unexpected operation '+b.operation);};
const formatCollaborationStatusTimestamp=()=> '15 Jan, 09:00',formatCollaborationSourceTimestamp=()=> '15 Jan, 09:00';
function Harness(){const [projection,setProjection]=useState(server),[opened,setOpened]=useState(true),[mode,setMode]=useState('access'),[themeMode,setTheme]=useState('light');const activeCollaborationOwnerProjection=mode==='start'?null:projection,activeCollaborationMessage={id:'mail-1',subject:projection.source.subject},collaborationOwnerProjection={status:mode==='start'?'not_found':'success'},hasActiveCollaborationOwnerProjection=mode!=='start',hasActiveCollaborationOwnerLifecycle=true;
const [isCollaborationSecureLinkVisible,setIsCollaborationSecureLinkVisible]=useState(false),[isCollaborationSecureLinkClosePending,setIsCollaborationSecureLinkClosePending]=useState(false);const closeCollaborationOverlay=()=>{setOpened(false);setIsCollaborationSecureLinkClosePending(false)};${guard}
useEffect(()=>{const key=e=>{if(e.key==='Escape')requestCloseCollaborationOverlay()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[isCollaborationSecureLinkVisible]);
const activeCollaborationSourceMailboxId='mailbox-google',activeCollaborationOwnerContextKey='ctx',currentViewerPersistenceKey='viewer',currentMemberUserId=owner,currentUserEmail='morgan@example.test',collaborationAccessPanelMode=mode,activeCollaborationOwnerLocator={mailboxId:'mailbox-google',sourceRef:{providerMessageId:'provider-message-1'}};
const teamMemberEntries=[{memberUserId:owner,name:'Morgan Lee',email:'morgan@example.test',status:'Active'},{memberUserId:teammate,name:'Sam Taylor',email:'sam@example.test',status:'Active'},{memberUserId:extra,name:'Jamie Chen',email:'jamie@example.test',status:'Active'}];const applyCanonicalCollaborationAccessResult=c=>{server=c;setProjection(c);setMode('access')},onCanonicalCollaborationMutation=()=>{};
const exactNotificationProjectionRef=useRef(null),collaborationMessageRefs=useRef({});const [highlightedCollaborationMessageId,setHighlight]=useState(null);const [collaborationOwnerSharedMessageDraft,setCollaborationOwnerSharedMessageDraft]=useState(''),[collaborationOwnerInternalNoteDraft,setCollaborationOwnerInternalNoteDraft]=useState(''),[collaborationOwnerSharedMessageState,setCollaborationOwnerSharedMessageState]=useState({status:'idle'}),[collaborationOwnerInternalNoteState,setCollaborationOwnerInternalNoteState]=useState({status:'idle'});const collaborationOwnerSharedMessageRequestRef=useRef(null),collaborationOwnerInternalNoteRequestRef=useRef(null);
const append=async internal=>{const prepared=(internal?prepareInternalCollaborationMessageForOwner:prepareSharedCollaborationMessageForOwner)(id,internal?collaborationOwnerInternalNoteDraft:collaborationOwnerSharedMessageDraft);if(prepared.status!=='ready')throw Error(prepared.status);const result=await prepared.operation.execute();if(result.status!=='success')throw Error(result.status);setProjection({...server});(internal?setCollaborationOwnerInternalNoteDraft:setCollaborationOwnerSharedMessageDraft)('')};const submitCollaborationOwnerSharedMessage=()=>append(false),submitCollaborationOwnerInternalNote=()=>append(true),collaborationLifecycleStatus='idle',transitionCanonicalCollaboration=async()=>{const result=await(projection.state==='resolved'?reopenCollaborationForOwner:resolveCollaborationForOwner)(projection);if(result.status!=='success')throw Error(result.status);setProjection(result.collaboration)};
const binding={summary:{mailboxId:'mailbox-google',collaborationId:id}},currentCollaborationOpenBindingRef=useRef(binding),isCurrentCollaborationOpenBinding=(a,b)=>a.summary.collaborationId===b.summary.collaborationId,message=activeCollaborationMessage,openCollaborationOverlay=(mail,options)=>{window.__opened={mail,options};setOpened(true)};
window.__start=()=>{setMode('start');setOpened(true)};window.__theme=setTheme;window.__long=()=>setProjection({...projection,source:{...projection.source,subject:'LongSubject'.repeat(35)},messages:Array.from({length:25},(_,i)=>({...original.messages[i%2],id:'activity-'+i,text:'LongWord'.repeat(45)}))});window.__target=id=>{setHighlight(id);const node=collaborationMessageRefs.current[id];node.scrollIntoView({block:'center'});node.focus()};
return <><div className="p-4">${cta}</div>{opened?<>${modal}{isCollaborationSecureLinkClosePending?<div role="alertdialog" aria-label="Close the one-time secure link?" className="fixed inset-x-6 top-10 z-[400] rounded-2xl bg-[var(--workspace-card)] p-4 shadow-panel"><p>Save the link before closing.</p><button onClick={()=>setIsCollaborationSecureLinkClosePending(false)}>Back</button><button onClick={closeCollaborationOverlay}>Close anyway</button></div>:null}</>:null}</>}
createRoot(document.getElementById('root')).render(<React.StrictMode><Harness/></React.StrictMode>);`;
const bundle=await build({stdin:{contents:fixture,loader:'tsx',resolveDir:dir},bundle:true,write:false,jsx:'automatic',plugins:baseline?[{name:'baseline-access',setup(b){b.onLoad({filter:/CollaborationAccessPanel\.tsx$/},()=>({contents:access,loader:'tsx',resolveDir:dir}));}}]:[]});
const css=await postcss([tailwind({...config,content:[{raw:source,extension:'tsx'},{raw:access,extension:'tsx'},{raw:fixture,extension:'tsx'}]})]).process(fs.readFileSync(path.join(dir,'../../index.css'),'utf8'),{from:undefined});
const assets={'/':['text/html','<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><meta charset="UTF-8"><title>C3P1 fixture</title><link rel="stylesheet" href="/style.css"></head><body><div id="root"></div><script src="/app.js"></script></body></html>'],'/app.js':['text/javascript',bundle.outputFiles[0].text],'/style.css':['text/css',css.css]};const srv=http.createServer((req,res)=>{const a=assets[req.url];if(!a){res.writeHead(404).end();return;}res.setHeader('Content-Type',a[0]);res.end(a[1]);});await new Promise(r=>srv.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+srv.address().port,output=fs.mkdtempSync(path.join(os.tmpdir(),baseline?'c3p1-before-':'c3p1-browser-'));let browser,passed=0;const pass=n=>{passed++;console.log('PASS '+n)};
console.log("ARTIFACTS "+output);
try{browser=await chromium.launch({headless:true,channel:'chrome'});const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.route('**/*',r=>r.request().url().startsWith(origin+'/')?r.continue():r.abort());
for(const [name,width,height] of [['desktop',1600,1000],['laptop',1280,800],['tablet',768,1024],['mobile',375,812]]){await page.setViewportSize({width,height});await page.goto(origin);await page.locator('[data-collaboration-thread-modal]').waitFor();await page.screenshot({animations:'disabled',path:output+'/'+name+'.png'});const metrics=await page.evaluate(()=>{const m=document.querySelector('[data-collaboration-thread-modal]'),b=m.querySelector('[data-collaboration-scroll-body]')||m.children[1];return {height:m.getBoundingClientRect().height,content:b.scrollHeight,viewport:b.clientHeight,overflow:document.documentElement.scrollWidth>innerWidth,scrollContainers:[...m.querySelectorAll('*')].filter(e=>getComputedStyle(e).overflowY==='auto'&&e.scrollHeight>e.clientHeight).length,layerHeight:m.parentElement.getBoundingClientRect().height};});console.log('METRICS '+name+' '+JSON.stringify(metrics));if(!baseline){assert.equal(metrics.overflow,false);assert.equal(metrics.scrollContainers,metrics.content>metrics.viewport?1:0);assert.ok(metrics.layerHeight<=height);const close=page.getByRole('button',{name:'Close collaboration',exact:true});assert.equal(await close.count(),1);assert.equal(await page.locator('[data-collaboration-thread-modal] button').evaluateAll(nodes=>nodes.filter(n=>n.textContent.trim()==='Close').length),1);await close.focus();assert.equal(await close.evaluate(e=>getComputedStyle(e).outlineStyle),'solid');assert.ok((await close.boundingBox()).height>=40);await page.getByRole('button',{name:'Resolve Collaboration',exact:true}).scrollIntoViewIfNeeded();pass(name+' layout, single scroll, close focus and reachable lifecycle');}}
if(!baseline){await page.setViewportSize({width:1280,height:900});await page.goto(origin);assert.equal(await page.locator('[data-collaboration-lifecycle-status]').count(),1);assert.equal(await page.locator('[data-guest-status]').count(),5);assert.equal(await page.locator('[data-guest-status="revoked"] button').count(),0);pass('one status and all five guest states retained');assert.deepEqual(await page.evaluate(()=>window.__calls),[]);assert.equal(await page.evaluate(()=>window.__intervals),0);pass('zero render-time requests or intervals');await page.getByRole('button',{name:'Close collaboration',exact:true}).focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'SUMMARY');await page.keyboard.press('Enter');await page.getByText('Alex Rivera · alex@example.test · 15 Jan, 09:00',{exact:true}).waitFor();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'TEXTAREA');assert.deepEqual(await page.evaluate(()=>window.__calls),[]);pass('logical tab order and keyboard source disclosure without requests');
await page.getByRole('button',{name:'Add Team member',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('combobox').selectOption('usr_'+'C'.repeat(21)+'A');await page.locator('form').getByRole('button',{name:'Add Team member',exact:true}).click();await page.getByText('Jamie Chen',{exact:true}).waitFor();pass('real AccessPanel adds Team through real owner client');
await page.getByRole('button',{name:'Invite external guest',exact:true}).click();await page.getByRole('textbox',{name:'Email (optional)'}).fill('new@example.test');await page.getByRole('button',{name:'Create secure link',exact:true}).click();const link=page.locator('[data-collaboration-secure-link] input');await link.waitFor();assert.ok((await link.inputValue()).includes('T'.repeat(43)));await page.getByRole('button',{name:'Copy secure link',exact:true}).click();await page.getByText('Link copied',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),await link.inputValue());assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);pass('invite, transient link, clipboard, no persistence');
await page.getByRole('button',{name:'Close collaboration',exact:true}).click();await page.getByRole('alertdialog',{name:'Close the one-time secure link?'}).waitFor();await page.getByRole('alertdialog').getByRole('button',{name:'Back',exact:true}).click();assert.ok(await link.isVisible());await page.keyboard.press('Escape');await page.getByRole('alertdialog').waitFor();await page.getByRole('alertdialog').getByRole('button',{name:'Back',exact:true}).click();pass('production close guard protects button and Escape');await page.setViewportSize({width:375,height:812});await link.scrollIntoViewIfNeeded();await page.screenshot({animations:'disabled',path:output+'/mobile-link.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.ok((await link.boundingBox()).width>150);pass('mobile secure link usable');await page.getByRole('button',{name:'Close link',exact:true}).click();await page.getByRole('button',{name:'Close anyway',exact:true}).click();assert.equal(await link.count(),0);pass('Close link preserves loss confirmation');
await page.setViewportSize({width:1280,height:900});const guest=page.locator('[data-guest-status="active"]').first();await guest.getByRole('button',{name:'Revoke access',exact:true}).focus();await page.keyboard.press('Enter');await guest.getByRole('alertdialog').getByRole('button',{name:'Revoke access',exact:true}).click();await page.locator('[data-guest-status="revoked"]').filter({hasText:'Alex Rivera'}).waitFor();pass('revoke confirmation and history retained');
await page.getByRole('textbox',{name:'Shared Message',exact:true}).fill('Shared browser message');await page.getByRole('button',{name:'Add Shared Message',exact:true}).click();await page.getByText('Shared browser message',{exact:true}).waitFor();await page.getByRole('textbox',{name:'Internal Note',exact:true}).fill('Internal browser note');await page.getByRole('button',{name:'Add Internal Note',exact:true}).click();await page.getByText('Internal browser note',{exact:true}).waitFor();pass('production composers use distinct real append clients');
await page.getByRole('button',{name:'Resolve Collaboration',exact:true}).click();await page.getByRole('button',{name:'Reopen Collaboration',exact:true}).waitFor();assert.equal(await page.locator('[data-collaboration-lifecycle-status]').innerText(),'Ended');await page.screenshot({animations:'disabled',path:output+'/resolved.png'});await page.getByRole('button',{name:'Reopen Collaboration',exact:true}).click();await page.getByRole('button',{name:'Resolve Collaboration',exact:true}).waitFor();pass('resolve and reopen canonical responses');
await page.keyboard.press('Escape');await page.locator('[data-collaboration-thread-modal]').waitFor({state:'detached'});const open=page.getByRole('button',{name:'Open Collaboration',exact:true});assert.equal(await open.count(),1);assert.ok((await open.boundingBox()).width<200);await open.focus();await page.keyboard.press('Enter');await page.locator('[data-collaboration-thread-modal]').waitFor();assert.equal((await page.evaluate(()=>window.__opened)).options.expectedBinding.summary.collaborationId,'A'.repeat(22));assert.equal(await link.count(),0);pass('keyboard Close, compact unique CTA and exact ID; no token redisplay');
await page.evaluate(()=>window.__long());await page.locator('[data-collaboration-activity-id="activity-24"]').waitFor();await page.evaluate(()=>window.__target('activity-24'));await page.waitForFunction(()=>document.activeElement?.getAttribute('data-notification-highlighted')==='true');await page.setViewportSize({width:375,height:812});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('long content wraps; activity ref, focus and highlight retained');
await page.goto(origin);await page.evaluate(()=>window.__theme('dark'));await page.locator('[data-collaboration-thread-modal][data-theme="dark"]').waitFor();await page.screenshot({animations:'disabled',path:output+'/dark.png'});await page.evaluate(()=>window.__start());await page.getByRole('radio',{name:/External guest/}).check();await page.setViewportSize({width:375,height:812});await page.screenshot({animations:'disabled',path:output+'/mobile-start.png'});assert.equal(await page.getByRole('textbox',{name:/Email \(optional\)/}).count(),1);assert.equal(await page.getByRole('radio',{name:/Jamie Chen/}).count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('compact participant selector only shows selected form');assert.deepEqual(errors,[]);pass('no browser or React errors; nonlocal traffic blocked');}console.log('RESULT '+passed+' focused browser checks; artifacts '+output);
}finally{await browser?.close();srv.close();}
